version: '3.8'
services:
  studify-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - JWT_EXPIRATION=86400
      - JWT_ISSUER=studify-api
      - ADMIN_REGISTRATION_TOKEN=admin-secret-token
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped